version: "2"

run:
  timeout: 5m

linters:
  enable:
    - ineffassign
    - unused
    - staticcheck
  disable:
    - errcheck

issues:
  exclude-dirs:
    - examples

  exclude-rules:
    # Suppress all linters in test files
    - path: "_test\\.go$"
      linters:
        - ineffassign
        - unused
        - staticcheck
